### ISSUE TITLE
No menu for mobile

### ISSUE THREAD

**Issue by progerg** [aminalaee/sqladmin#356] opened 2022-10-13 11:33 UTC
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When I log in from mobile there is no menu at the left side of the screen and there is no way no navigate between pages

### Steps to reproduce the bug

1) Open the admin from mobile or make the browser window smaller
![Screenshot](https://user-images.githubusercontent.com/69199324/195585062-7e5ca0cb-d9df-4dac-9ca6-3809335c6925.png)

### Expected behavior

I expected something like menu at the top of the page or some button to open the menu

### Actual behavior

When the page is opened from small screen mobiles there are no buttons, empty page only

### Environment

- Browser: Google, Firefox

**Comment by aminalaee** [comment] 2022-10-13 20:07
Hi,
Thanks for raising this. This is a duplicate of https://github.com/aminalaee/sqladmin/issues/283
My knowledge of CSS is very limited but I think it should be simple. Feel free to create a PR for it

**Closed** 2022-10-27 07:08 UTC
