### ISSUE TITLE
Support for .with_variant() types

### ISSUE THREAD

**Issue by DanielSchiessl** [aminalaee/sqladmin#138] opened 2022-04-22 06:16 UTC
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

When using BigIntegers in sqlalchemy together with "with_variant", e.g. `Column(BigInteger().with_variant(Integer, "sqlite"))` the error _"Could not find field converter for column id (<class 'sqlalchemy.sql.type_api.Variant'>)"_ is thrown.

### Describe alternatives you considered

_Using form_overrides seems to work fine as workaround however native support would be much appreciated :)_

**Comment by aminalaee** [comment] 2022-06-06 19:55
Hey @DanielSchiessl ,

I've spent some time but I could not find a sane way to solve this, the issue is, as you might already know, you're creating a new type dynamically which is not defined within SQLAdmin.

If you know or could find any way to get the column type for the variant, please update this issue, otherwise we can close this as the workaround is to define the `for_overrides` and work around this.

**Closed** 2022-06-10 10:50 UTC
Labels: waiting-for-feedback
