### ISSUE TITLE
DatieTime field is editable even after setting it as readonly

### ISSUE THREAD

**Issue by 94929** [aminalaee/sqladmin#332] opened 2022-09-24 11:40 UTC
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

DatieTime field is editable even after setting it as readonly field
![CleanShot 2022-09-24 at 20 38 11](https://user-images.githubusercontent.com/10961008/192095904-08246edc-e664-402e-818a-776c5b7ec927.png)

### Steps to reproduce the bug

Add this code to Admin class that inherits ModelView.
```
form_widget_args = {
    ...
    'created_at': { 'readonly': True },
}
```

### Expected behavior

Create At (DateTime) field is not editable.

### Actual behavior

Create At (DateTime) field is editable.

### Environment

OS - Ubuntu
Python - 3.9
SQLAdmin - latest
FastAPI

**Comment by aminalaee** [comment] 2022-09-24 12:49
Thanks for reporting this, yes this is a regression since we started using Flatpickr Date/Time pickers.
Fix is on the way.

**Comment by aminalaee** [comment] 2022-09-24 16:52
Thanks for reporting this @94929 . This is merged.

**Closed by aminalaee** 2022-09-24 16:52 UTC

**Comment by 94929** [comment] 2022-09-25 03:35
@aminalaee Thanks for the quick fix. When do you expect this fix to be deployed to pypi?

**Comment by aminalaee** [comment] 2022-09-25 12:09
I'll try today or tomorrow to release 0.6.1
